"""RFC 7807 Problem Details Schema."""

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class ProblemDetails(BaseModel):
    """RFC 7807 Problem Details representation."""

    type: str = Field(
        ...,
        description="A URI reference that identifies the problem type.",
        examples=["https://api.travelai.internal/errors/unsupported-media-type"],
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type.",
        examples=["Unsupported Media Type"],
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server.",
        examples=[415],
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence of the problem.",
        examples=[
            "File type application/pdf is not supported. Allowed: image/jpeg, image/png, image/webp"
        ],
    )
    instance: str | None = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
    )
    invalid_params: list[dict[str, Any]] | None = Field(
        None,
        description="Detailed parameter-level validation errors if applicable.",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="Timestamp in ISO 8601 UTC when the error occurred.",
    )
